In [1]:
%load_ext tutormagic

# ====================== Video 2 =======================

# Order of Recursive Calls
Understanding the order of recursive calls is important in understanding the behavior of recursive functions. It is important to remember that when we make a function call, we can't do anything else until the function reaches a `return`.

## The Cascade Function
The `cascade` function takes a positive integer `n` .

In [2]:
def cascade(n):
    if n < 10:
        print(n)
    else:
        print(n)
        cascade(n//10)
        print(n)

If we call `cascade` on a single number,

In [3]:
cascade(5)

5


It might seemed that `cascade` doesn't do much. However, if we call `cascade` on a large number,

In [4]:
cascade(12345)

12345
1234
123
12
1
12
123
1234
12345


`cascade` creates a pattern! The way it works is that the second `print` statement prints number again (e.g. the second `12345`), but it won't be executed until Python finishes executing `cascade(n//10)`

Let's analyze the environment diagram!

In [ ]:
%%tutor --lang python3

def cascade(n):
    if n < 10:
        print(n)
    else:
        print(n)
        cascade(n//10)
        print(n)
        
cascade(123)

In the following step:

2. Python defines `cascade`
    * Binds the function `cascade(n)` to the name `cascade`

3. Python executes `cascade(123)`
    * Creates a new frame `f1` with formal parameter `n` = `123`
    
4. Checks if `n` < `10`. No, move on

6. Prints `123`

7. Recursive call of `cascade(n//10)`, which is `cascade(12)`
    * Creates a new frame `f2` with formal parameter `n` = `12`
    * **NOTE THAT** here Python still yet to finish the second `print` statement. This `print` statement is delayed until Python finishes executing `cascade(12)`. Here Python delays the `print(123)`
    
8. Checks if `12` < `10`. No, move on

10. Prints `12`

11. Recursive call of `cascade(n//10)` once again, which is `cascade(1)`
    * Creates a new frame `f3` with formal parameter `n` = `1`
    * Delays the second `print(12)`

13. Checks if `1` < `10`. Yes!

14. Prints `1`
    * Obtain a return value `None` since there is no `return` statement at all
    
15. Python goes back to frame `f2`, attempting to finish the rest of the execution, which is to print the delayed `print(12)`

16. Prints the second `12`, and we obtain return value `None` again because there is no `return` statement

17. Python goes back to frame `f3`, attempting to finish the rest of `f3` execution as well, which is to print the delayed `print(123)`

18. Python prints the second `123`.

Some things to remember:
1. Each cascade frame is from a different call to cascade
2. Until the `Return` value appears, that call has not completed 
3. Any statement can appear before or after the recursive call
    * before: the first `print` statement
    * after: the second `print` statement, after the `cascade(n//10)` statement
    
<img src = 'cascade.jpg' width = 400/>

Above shows that the frame `f2` is responsible for printing `12` on both sides before and after `1`.


## Two Definitions of Cascade
What we defined earlier is not the only way to define cascade. Below is a shorter way of defining `cascade`.

In [1]:
def cascade(n):
    print(n)
    if n > 10:
        cascade(n//10)
        print(n)

Let's try this new function!

In [2]:
cascade(12345)

12345
1234
123
12
1
12
123
1234
12345


Which implementation is better? The previous one or the new, shorter one?
1. If the 2 implementations are equally clear, the shorter one is usually better
2. In some cases, the longer version is more clear since it indicates the base case and the recursive case
3. When learning to write recursive functions, put the base cases first
4. Both are recursive functions, even though only the first one has the typical structure

If we are deciding between which implementation to use, keep in mind that often times, we write code for someone else to use.

# ========================= Video 3 =========================

## Inverse Cascade
This time, we'll write a function that prints an inverse cascade. An inverse cascade look like the following,

1
12
123
1234
123
12
1

We will be using the following structure, `inverse cascade` for the implementation,

In [2]:
def inverse_cascade(n):
    grow(n)
    print(n)
    shrink(n)

<img src = 'inverse.jpg' width = 500/>

As we can see above,:
1. The `grow` function is responsible for the first three lines, `1`, `12`, and `123`.
    * It's called `grow` because for every line, it grows longer
2. The `print` function is responsible for the middle line (or the longest line)
3. The `shrink` function is responsible for the rest.
    * It's called `shrink` because for every line, it shrinks (becomes shorter)
    
Both `grow` and `shrink` will be related to the following higher-order function `f_then_g`, which takes in 2 functions `f` and `g` and a number `n`. The function will call `f`, then call `g`. 

In [3]:
def f_then_g(f, g, n):
    if n: # if n is not 0
        f(n)
        g(n)

Now we'll define `grow` and `shrink` while making use of `f_then_g`.

In [5]:
grow = lambda n: f_then_g(grow, print, n // 10)

The `grow` implementation above makes sense. When we call `inverse_cascade(1234)`, Python will call `grow(1234)`.

1. `grow(1234)` means:
    * Call `grow(123)`
    * Prints (1234)
    
But the `print(1234)` won't be executed until Python finishes calling `grow(123)`.

2. `grow(123)` means:
    * Call `grow(12)`
    * print(`123`)
    
Again, the `print(123)` won't be executed until Python finishes calling `grow(12)`

The steps repeats until `n` reaches `0`. At this point, the printing starts from the first digit `1`.

Meanwhile, the implementation for `shrink` is the opposite of `grow`.

In [6]:
shrink = lambda n: f_then_g(print, shrink, n // 10)

In [7]:
grow(1234)

1
12
123


In [8]:
shrink(1234)

123
12
1


# ========================= Video 4 =========================

# Tree Recursion
Tree recursion occurs when a function makes more than one recursive call.

Tree-shaped processes arise whenever executing the body of a recursive function makes more than one call to that function. 

An example of tree recursion is the **Fibonacci Sequence**. 

<img src = 'fib.jpg' width = 500/>

Above, we have the index at the top and the fibonacci number at the bottom. This means the 2nd Fibonacci number is 1, the 3rd is 2. 

See that at first, the Fibonacci number grows slow. However, as the index rises, the increase in Fibonacci number becomes much greater. The `35`th Fibonacci number is `9,227,465`!

Below we define the `fib` function, where the base cases cover when `n` is `0` and `1`, while the recursive case sums the previous 2. 

In [10]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        # Below is the tree recursion
        return fib(n-2) + fib(n-1)

The `fib` above is a tree recursive function since to compute `fib`, we need to call `fib` twice. 

## A Tree-Recursive Process
The computational process of `fib` evolves into a tree structure. 

Below we have a **tree structure** of calling `fib(5)`:

<img src = 'tree.jpg' width = 700/>

How to read the tree above:

1. Calling `fib(5)` involves calling `fib(3)` and `fib(4)`
    * Calling `fib(3)` involves calling `fib(1)` and `fib(2)`
        * `fib(1)` is a base case that returns `1`
        * Calling `fib(2)` involves calling `fib(0)` and `fib(1)`
            * `fib(0)` is a base case that returns `0`
            * `fib(1)` is a base case that returns `1`
            
And the same thing for `fib(4)`. 

It is called a **tree structure** because if we flip it, the structure will look like a tree. 

The computation works as the following,

<img src = 'tree_2.jpg' width = 700/>

1. To calculate `fib(5)` we need to know the value of `fib(3)` and `fib(4)`
    * To calculate `fib(3)`, we need to know the value of `fib(1)` and `fib(2)`
        * The value of `fib(1)` is `1`
        * To calculate `fib(2)`, we need to know the value of `fib(0)` and `fib(1)`
            * The value of `fib(0)` is `0`
            * The value of `fib(1)` is `1`

Once we know the value of `fib(3)`, we then find out the value of `fib(4)`

## Demo
Let's test out the `fib` function!

In [11]:
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        # Below is the tree recursion
        return fib(n-2) + fib(n-1)

In [12]:
fib(0)

0

In [13]:
fib(1)

1

In [14]:
fib(2)

1

In [15]:
fib(3)

2

In [16]:
fib(5)

5

In [17]:
fib(8)

21

In [18]:
fib(10)

55

In [19]:
fib(20)

6765

In [20]:
fib(30)

832040

Notice that when we compute `fib(30)`, the computation takes longer! What's going on?

To analyze what's going on, we'll use the `trace` decorator that we used previously from the `ucb` module. Recall the `trace` decorator changes a function's behavior so that it prints out:
1. When it gets called
2. When it returns

In [21]:
from ucb import trace

@trace
def fib(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    else:
        # Below is the tree recursion
        return fib(n-2) + fib(n-1)

In [22]:
fib(0)

fib(0):
fib(0) -> 0


0

In [23]:
fib(1)

fib(1):
fib(1) -> 1


1

For `fib(0)` and `fib(1)`, since both are base cases, the traces are simple. However, when we call `fib(2)`,

In [24]:
fib(2)

fib(2):
    fib(0):
    fib(0) -> 0
    fib(1):
    fib(1) -> 1
fib(2) -> 1


1

`fib(2)` involves calling `fib(0)` and `fib(1)`! `fib(0)` returns `0` and `fib(1)` returns `1`. Summing them together, the result of calling `fib(2)` is 1!

In [25]:
fib(3)

fib(3):
    fib(1):
    fib(1) -> 1
    fib(2):
        fib(0):
        fib(0) -> 0
        fib(1):
        fib(1) -> 1
    fib(2) -> 1
fib(3) -> 2


2

In [26]:
fib(5)

fib(5):
    fib(3):
        fib(1):
        fib(1) -> 1
        fib(2):
            fib(0):
            fib(0) -> 0
            fib(1):
            fib(1) -> 1
        fib(2) -> 1
    fib(3) -> 2
    fib(4):
        fib(2):
            fib(0):
            fib(0) -> 0
            fib(1):
            fib(1) -> 1
        fib(2) -> 1
        fib(3):
            fib(1):
            fib(1) -> 1
            fib(2):
                fib(0):
                fib(0) -> 0
                fib(1):
                fib(1) -> 1
            fib(2) -> 1
        fib(3) -> 2
    fib(4) -> 3
fib(5) -> 5


5

As we can see, calling `fib(5)` results in a tree structure. We can see that there are a lot of work Python needs to do to compute `fib(5)`! Now imagine calling `fib(10)` and `fib(30)`.

In [27]:
fib(10)

fib(10):
    fib(8):
        fib(6):
            fib(4):
                fib(2):
                    fib(0):
                    fib(0) -> 0
                    fib(1):
                    fib(1) -> 1
                fib(2) -> 1
                fib(3):
                    fib(1):
                    fib(1) -> 1
                    fib(2):
                        fib(0):
                        fib(0) -> 0
                        fib(1):
                        fib(1) -> 1
                    fib(2) -> 1
                fib(3) -> 2
            fib(4) -> 3
            fib(5):
                fib(3):
                    fib(1):
                    fib(1) -> 1
                    fib(2):
                        fib(0):
                        fib(0) -> 0
                        fib(1):
                        fib(1) -> 1
                    fib(2) -> 1
                fib(3) -> 2
                fib(4):
                    fib(2):
                        fib(0):
                        fib

55

## Repetition in Tree-Recursive Computation
The `fib` function that we have defined is not an efficient way to compute the fibonacci number. The process is highly repetitive: `fib` is called on the same argument multiple times.

<img src = 'remember.jpg' width = 700/>

As we can see above, the parts that are written in green font are the repeated computations. It would be nice if we can remember or store such results that if they are being called once again, we can just pull out the stored results. (We'll actually cover about this in future lectures).

# ========================= Video 5 =========================

# Example: Counting Partitions
Counting partitions is a tree-recursive process that's difficult to write without tree recursion. One of the few reasons we learn about partition in this course is to solve problems like this.

## Counting Partitions
The number of partitions of a positive integer `n`, using parts up to size `m`, is the number of ways in which `n` can be expressed as the sum of positive integer parts up to `m` in increasing order. 

For example, let's say we want to calculate `count_partitions(6, 4)`. This means we want all the calculations that counts to `6` using parts with sizes up to `4`. 

The following is the partitions:

<img src = 'partition.jpg' width = 800/>

Notice that all the sums are expressed in increasing order (e.g. `2 + 4`, but we don't have `4 + 2`). Also notice that the biggest number that it uses is `4`. The right side is an illustration of the grouping. 

The idea is that we're counting the number of ways `6` can be broken down to groups. In this case, we see that there are `9` different ways and thus, `count_partitions(6, 4)` should return `9`. 

To calculate the partitions, we need a strategy.

## Strategy for Counting Partitions
1. Recursive Decomposition: express the problem in terms of simpler instances of the same problem. 
2. We can do recursive decomposition by exploring 2 possibilities:
    * Use at least one group of `4` in the sum calculation
    * Don't use any `4` (use parts up to `3` max)
    
Below is a representation of splitting the problem to 2 groups: using `4` (the 2 partitions at the top) and not using any `4` (the rest):

<img src = 'partition_split.jpg' width = 500/>

3. Solve 2 simpler problems by making 2 separate recursive calls:

<img src = 'simpler.jpg' width = 700/>

When we call `count_partitions(6, 3)`, we can execute another recursive decomposition, separating the problem once again to smaller problems: using `3` and not using any `3`.
    * `count_partition(3, 3)`
    * `count_partition(6, 2)`

<img src = 'simpler_2.jpg' width = 700/>

With the `count_partition(6, 2)` call, we can still execute another recursive decomposition! 

<img src = 'simpler_3.jpg' width = 700/>

Tree recursion can be considered a technique that explores different choices or possibilities.



## Writing the Implementation
We define `count_partitions(n, m)` that counts the partitions of an integer `n` using parts up to size `m`.

In [ ]:
def count_partitions(n, m):

The **recursive decomposition** that we discussed earlier is part of the recursive case. Let's implement that first!

In [ ]:
else:
    # Count the partition of n-m using parts up to size m
    with_m = count_partitions(n-m, m)
    # Count the partition of n using parts that are smaller than m
    without_m = count_partitions(n, m-1)
    # Sum the cases where we used m and the cases where we did not
    return with_m + without_m

<img src = 'implement.jpg' width = 800/>

Now we can start implementing base cases.
1. If `n` is `0`, or if we are partitioning `0`, there's only 1 way to do it: just use `0`
2. If `n` < `0`, or if we are partitioning a negative number, this is impossible. Thus, there's `0` way to do this
3. If `m` == `0`, or if we can only use parts up to `0`, then we can't make anything with this. Thus, there's `0` way.

In [ ]:
def count_partitions(n, m):
    if n == 0:
        return 1
    elif n < 0:
        return 0
    elif m == 0:
        return 0
    else:
        with_m = count_partitions(n-m, m)
        without_m = count_partitions(n, m-1)
        return with_m + without_m