In [1]:
%load_ext tutormagic

# Order of Recursive Calls
Understanding the order of recursive calls is important in understanding the behavior of recursive functions. It is important to remember that when we make a function call, we can't do anything else until the function reaches a `return`.

## The Cascade Function
The `cascade` function takes a positive integer `n` .

In [2]:
def cascade(n):
    if n < 10:
        print(n)
    else:
        print(n)
        cascade(n//10)
        print(n)

If we call `cascade` on a single number,

In [3]:
cascade(5)

5


It might seemed that `cascade` doesn't do much. However, if we call `cascade` on a large number,

In [4]:
cascade(12345)

12345
1234
123
12
1
12
123
1234
12345


`cascade` creates a pattern! The way it works is that the second `print` statement prints number again (e.g. the second `12345`), but it won't be executed until Python finishes executing `cascade(n//10)`

Let's analyze the environment diagram!

In [ ]:
%%tutor --lang python3

def cascade(n):
    if n < 10:
        print(n)
    else:
        print(n)
        cascade(n//10)
        print(n)
        
cascade(123)

In the following step:

2. Python defines `cascade`
    * Binds the function `cascade(n)` to the name `cascade`

3. Python executes `cascade(123)`
    * Creates a new frame `f1` with formal parameter `n` = `123`
    
4. Checks if `n` < `10`. No, move on

6. Prints `123`

7. Recursive call of `cascade(n//10)`, which is `cascade(12)`
    * Creates a new frame `f2` with formal parameter `n` = `12`
    * **NOTE THAT** here Python still yet to finish the second `print` statement. This `print` statement is delayed until Python finishes executing `cascade(12)`. Here Python delays the `print(123)`
    
8. Checks if `12` < `10`. No, move on

10. Prints `12`

11. Recursive call of `cascade(n//10)` once again, which is `cascade(1)`
    * Creates a new frame `f3` with formal parameter `n` = `1`
    * Delays the second `print(12)`

13. Checks if `1` < `10`. Yes!

14. Prints `1`
    * Obtain a return value `None` since there is no `return` statement at all
    
15. Python goes back to frame `f2`, attempting to finish the rest of the execution, which is to print the delayed `print(12)`

16. Prints the second `12`, and we obtain return value `None` again because there is no `return` statement

17. Python goes back to frame `f3`, attempting to finish the rest of `f3` execution as well, which is to print the delayed `print(123)`

18. Python prints the second `123`.

Some things to remember:
1. Each cascade frame is from a different call to cascade
2. Until the `Return` value appears, that call has not completed 
3. Any statement can appear before or after the recursive call
    * before: the first `print` statement
    * after: the second `print` statement, after the `cascade(n//10)` statement
    
<img src = 'cascade.jpg' width = 400/>

Above shows that the frame `f2` is responsible for printing `12` on both sides before and after `1`.


## Two Definitions of Cascade
What we defined earlier is not the only way to define cascade. Below is a shorter way of defining `cascade`.

In [1]:
def cascade(n):
    print(n)
    if n > 10:
        cascade(n//10)
        print(n)

Let's try this new function!

In [2]:
cascade(12345)

12345
1234
123
12
1
12
123
1234
12345


Which implementation is better? The previous one or the new, shorter one?
1. If the 2 implementations are equally clear, the shorter one is usually better
2. In some cases, the longer version is more clear since it indicates the base case and the recursive case
3. When learning to write recursive functions, put the base cases first
4. Both are recursive functions, even though only the first one has the typical structure

If we are deciding between which implementation to use, keep in mind that often times, we write code for someone else to use.